services:
  postgres:
    image: postgres:17
    container_name: archflow_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=archflow
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: archflow_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: always

volumes:
  postgres-data:
  minio-data: